apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    component: kube-scheduler
  name: kube-scheduler
  namespace: monitoring
spec:
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: token
      name: prometheus-k8s-token
    interval: 30s
    port: https-metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      component: kube-scheduler
