apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: korrel8r
commonLabels:
  app.kubernetes.io/name: korrel8r
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - clusterrolebinding.yaml
