# permissions for end users to edit korrel8rs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: korrel8r-editor-role
rules:
- apiGroups:
  - korrel8r.openshift.io
  resources:
  - korrel8rs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - korrel8r.openshift.io
  resources:
  - korrel8rs/status
  verbs:
  - get
