apiVersion: apps/v1
kind: Deployment
metadata:
  name: korrel8r
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: korrel8r
      app.kubernetes.io/component: engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: korrel8r
        app.kubernetes.io/component: engine
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: korrel8r
      containers:
      - name: korrel8r
        image: "quay.io/korrel8r/korrel8r"
        imagePullPolicy: Always
        command: ["korrel8r", "--verbose=4", "web", "--https", ":8443", "--cert", "/etc/secrets/tls.crt", "--key", "/etc/secrets/tls.key"]
# FIXME        /var/run/secrets/kubernetes.io/serviceaccount/token
        volumeMounts:
          - name: secrets
            readOnly: true
            mountPath: /etc/secrets
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
